version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: TodoDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "1234:5432"
    networks:
      - todo-app
    volumes:
      - db:/var/lib/db

  api:
    build:
      context: ./
      dockerfile: ./TodoApplication.Api/Dockerfile
    ports:
      - '80:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    depends_on:
      - db
    networks:
      - todo-app
    volumes:
      - api:/var/lib/car-service

networks:
  todo-app:

volumes:
  db:
  api: